---
language: go
go:
- "tip"
- "1.10"
- "1.9"
- "1.8"
# Require trusty because the older environment (Ubuntu precise) has only
# mysql 5.5 which lacks mysql_config_editor
dist: trusty
sudo: false
addons:
  apt:
    packages:
    # For mysql_config_editor
    - mysql-client-5.6
